/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lexismanage.vista;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JPanel;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
import lexismanage.Conexion;

/**
 *
 * @author alexi
 */
public class AccesoUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN
     */
    
    MenuConfiguracion CON= new MenuConfiguracion();
    
    public AccesoUsuarios() {
        initComponents();
         Conexion con=new Conexion();
        
        CON.mostrardatosest();
        NAMEEST.setText(CON.nameest);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        
       
       // this.setSize(1280, 720);
    }
    private void iniciarTemporizador() {
        Timer timer = new Timer(3000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                lblResultado.setText("");  
            }
        });
        timer.setRepeats(false); 
        timer.start();
    }
    private void verificarMembresia() {
        String identificacion = CAMPOIDUSUARIO.getText().trim();
        if (identificacion.isEmpty() || CAMPOIDUSUARIO.getText().equals(" Ingrese ID Usuario")) {
            lblResultado.setText("Debe ingresar una identificación.");
            iniciarTemporizador();
            return;
        }

        try (Connection conexion = Conexion.conectar()) {
            String sql = "SELECT u.nombre, u.apellido, e.estado FROM Usuario u " +
                         "JOIN EstadoMembresia e ON u.id_estado = e.id_estado " +
                         "JOIN Pago p ON u.id_usuario = p.id_usuario " +
                         "WHERE u.identificacion = ? AND p.fecha_fin >= NOW()";

            PreparedStatement pst = conexion.prepareStatement(sql);
            pst.setString(1, identificacion);

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                String nombre = rs.getString("nombre");
                String apellido = rs.getString("apellido");
                String estado = rs.getString("estado");

                if (estado.equals("Activa")) {
                    lblResultado.setText("Puedes ingresar, " + nombre + " " + apellido);
                    
                    
                    
                } else {
                    lblResultado.setText("No puedes ingresar, tu membresía está " + estado);
                }
            } else {
                lblResultado.setText("No se encontró un usuario con membresía activa.");
                
            }
             iniciarTemporizador();

        } catch (SQLException ex) {
            lblResultado.setText("Error al consultar la base de datos.");
            ex.printStackTrace();
             iniciarTemporizador();
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        LOGOLX = new javax.swing.JLabel();
        NAMEEST = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cerraracceso = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        CAMPOIDUSUARIO = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ingresaruser = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(10, 16, 30));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(10, 16, 30));
        jPanel1.setForeground(new java.awt.Color(10, 16, 30));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(26, 39, 55));

        LOGOLX.setFont(new java.awt.Font("FRISTA", 3, 14)); // NOI18N
        LOGOLX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lexismanage/images/LM100.png"))); // NOI18N

        NAMEEST.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        NAMEEST.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(NAMEEST, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 315, Short.MAX_VALUE)
                .addComponent(LOGOLX)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NAMEEST, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(LOGOLX, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(161, 161, 161))
        );

        jPanel3.setBackground(new java.awt.Color(26, 39, 55));

        cerraracceso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lexismanage/images/x lm.png"))); // NOI18N
        cerraracceso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerraraccesoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cerraracceso, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cerraracceso, javax.swing.GroupLayout.PREFERRED_SIZE, 86, Short.MAX_VALUE))
        );

        lblResultado.setFont(new java.awt.Font("Segoe UI Semibold", 3, 24)); // NOI18N
        lblResultado.setForeground(new java.awt.Color(255, 255, 255));

        CAMPOIDUSUARIO.setBackground(new java.awt.Color(242, 242, 242));
        CAMPOIDUSUARIO.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        CAMPOIDUSUARIO.setForeground(new java.awt.Color(153, 153, 153));
        CAMPOIDUSUARIO.setText(" Ingrese ID Usuario");
        CAMPOIDUSUARIO.setToolTipText("");
        CAMPOIDUSUARIO.setBorder(null);
        CAMPOIDUSUARIO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CAMPOIDUSUARIOMousePressed(evt);
            }
        });
        CAMPOIDUSUARIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAMPOIDUSUARIOActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID Usuario:");

        ingresaruser.setBackground(new java.awt.Color(255, 77, 88));
        ingresaruser.setFont(new java.awt.Font("Yu Gothic UI", 3, 18)); // NOI18N
        ingresaruser.setForeground(new java.awt.Color(242, 242, 242));
        ingresaruser.setText("Ingresar");
        ingresaruser.setBorder(null);
        ingresaruser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresaruserActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Acceso Usuarios ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ingresaruser, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CAMPOIDUSUARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(342, 342, 342)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CAMPOIDUSUARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ingresaruser, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerraraccesoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerraraccesoMouseClicked
        // TODO add your handling code here:
        Conexion.cerrarConexion();
        this.dispose();
    }//GEN-LAST:event_cerraraccesoMouseClicked

    private void CAMPOIDUSUARIOMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CAMPOIDUSUARIOMousePressed
        // TODO add your handling code here:

        if(CAMPOIDUSUARIO.getText().equals(" Ingrese ID Usuario")){
            CAMPOIDUSUARIO.setText("");
            CAMPOIDUSUARIO.setForeground(Color.black);
        }
    }//GEN-LAST:event_CAMPOIDUSUARIOMousePressed

    private void CAMPOIDUSUARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAMPOIDUSUARIOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CAMPOIDUSUARIOActionPerformed

    private void ingresaruserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresaruserActionPerformed
      
        verificarMembresia();
        CAMPOIDUSUARIO.setText(" Ingrese ID Usuario");
            CAMPOIDUSUARIO.setForeground(Color.gray);
    }//GEN-LAST:event_ingresaruserActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
      if(CAMPOIDUSUARIO.getText().isEmpty()){
            CAMPOIDUSUARIO.setText(" Ingrese ID Usuario");
            CAMPOIDUSUARIO.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jPanel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccesoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccesoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccesoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccesoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccesoUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CAMPOIDUSUARIO;
    private javax.swing.JLabel LOGOLX;
    private javax.swing.JLabel NAMEEST;
    private javax.swing.JLabel cerraracceso;
    private javax.swing.JButton ingresaruser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblResultado;
    // End of variables declaration//GEN-END:variables
}
