/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lexismanage.vista;

import java.awt.Color;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lexismanage.Conexion;
import static lexismanage.Conexion.conectar;

import lexismanage.LexisManage;

/**
 *
 * @author alexi
 */
public class LOGIN extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN
     */
    
   
      
    public LOGIN() {
        initComponents();
        this.setTitle("Login");
        Conexion conexion= new Conexion();
        Conexion.conectar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        LOGOLOGIN = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        CERRARLOGIN = new javax.swing.JLabel();
        PASSWORDLOGIN = new javax.swing.JLabel();
        USUARIOLOGIN = new javax.swing.JLabel();
        USUARIOLOGINCAMPO = new javax.swing.JTextField();
        PASSWORDLOGINCAMPO = new javax.swing.JPasswordField();
        BUTTONLOGIN = new javax.swing.JButton();
        BUTTONREGISTER = new javax.swing.JButton();
        OLVIDASTEPASSWORD = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(10, 16, 30));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(10, 16, 30));
        jPanel1.setForeground(new java.awt.Color(10, 16, 30));

        jPanel2.setBackground(new java.awt.Color(26, 39, 55));

        LOGOLOGIN.setFont(new java.awt.Font("FRISTA", 3, 14)); // NOI18N
        LOGOLOGIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lexismanage/images/LM100.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LOGOLOGIN)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LOGOLOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(26, 39, 55));

        CERRARLOGIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lexismanage/images/x lm.png"))); // NOI18N
        CERRARLOGIN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CERRARLOGINMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(772, Short.MAX_VALUE)
                .addComponent(CERRARLOGIN)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(CERRARLOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PASSWORDLOGIN.setFont(new java.awt.Font("Yu Gothic UI", 3, 24)); // NOI18N
        PASSWORDLOGIN.setForeground(new java.awt.Color(255, 255, 255));
        PASSWORDLOGIN.setText("Contraseña :");

        USUARIOLOGIN.setFont(new java.awt.Font("Yu Gothic UI", 3, 24)); // NOI18N
        USUARIOLOGIN.setForeground(new java.awt.Color(255, 255, 255));
        USUARIOLOGIN.setText("Usuario :");

        USUARIOLOGINCAMPO.setBackground(new java.awt.Color(242, 242, 242));
        USUARIOLOGINCAMPO.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        USUARIOLOGINCAMPO.setForeground(new java.awt.Color(153, 153, 153));
        USUARIOLOGINCAMPO.setText("ingrese su nombre de usuario");
        USUARIOLOGINCAMPO.setBorder(null);
        USUARIOLOGINCAMPO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                USUARIOLOGINCAMPOMousePressed(evt);
            }
        });
        USUARIOLOGINCAMPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USUARIOLOGINCAMPOActionPerformed(evt);
            }
        });

        PASSWORDLOGINCAMPO.setBackground(new java.awt.Color(242, 242, 242));
        PASSWORDLOGINCAMPO.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        PASSWORDLOGINCAMPO.setForeground(new java.awt.Color(153, 153, 153));
        PASSWORDLOGINCAMPO.setText("******");
        PASSWORDLOGINCAMPO.setBorder(null);
        PASSWORDLOGINCAMPO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PASSWORDLOGINCAMPOMousePressed(evt);
            }
        });
        PASSWORDLOGINCAMPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PASSWORDLOGINCAMPOActionPerformed(evt);
            }
        });

        BUTTONLOGIN.setBackground(new java.awt.Color(255, 77, 88));
        BUTTONLOGIN.setFont(new java.awt.Font("Yu Gothic UI", 3, 18)); // NOI18N
        BUTTONLOGIN.setForeground(new java.awt.Color(242, 242, 242));
        BUTTONLOGIN.setText("Iniciar Sesion");
        BUTTONLOGIN.setBorder(null);
        BUTTONLOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTONLOGINActionPerformed(evt);
            }
        });

        BUTTONREGISTER.setFont(new java.awt.Font("Yu Gothic UI", 3, 18)); // NOI18N
        BUTTONREGISTER.setForeground(new java.awt.Color(255, 77, 88));
        BUTTONREGISTER.setText("Registrarse");
        BUTTONREGISTER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTONREGISTERActionPerformed(evt);
            }
        });

        OLVIDASTEPASSWORD.setBackground(new java.awt.Color(171, 189, 201));
        OLVIDASTEPASSWORD.setFont(new java.awt.Font("Yu Gothic UI", 3, 18)); // NOI18N
        OLVIDASTEPASSWORD.setForeground(new java.awt.Color(255, 255, 255));
        OLVIDASTEPASSWORD.setText("Olvidaste Tu Contraseña?");
        OLVIDASTEPASSWORD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OLVIDASTEPASSWORDMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BUTTONLOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BUTTONREGISTER, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(235, 235, 235))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(OLVIDASTEPASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(325, 325, 325))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PASSWORDLOGINCAMPO, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(USUARIOLOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PASSWORDLOGIN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(USUARIOLOGINCAMPO, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(USUARIOLOGIN)
                .addGap(18, 18, 18)
                .addComponent(USUARIOLOGINCAMPO, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(PASSWORDLOGIN)
                .addGap(18, 18, 18)
                .addComponent(PASSWORDLOGINCAMPO, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BUTTONLOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BUTTONREGISTER, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(OLVIDASTEPASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void USUARIOLOGINCAMPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USUARIOLOGINCAMPOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_USUARIOLOGINCAMPOActionPerformed

    private void BUTTONLOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTONLOGINActionPerformed
        // TODO add your handling code here:
        
       String usuario = USUARIOLOGINCAMPO.getText();
    String password = new String(PASSWORDLOGINCAMPO.getPassword());

    if (!usuario.isEmpty() && !password.isEmpty()) {
        String consulta = "SELECT * FROM usuario_admin WHERE nombre_usuario = ? AND contrasena = ?";
        
        // Usar try-with-resources para asegurarse de cerrar los recursos
        try (
                Connection conn = Conexion.conectar(); // Obtén la conexión
             PreparedStatement ps = conn.prepareStatement(consulta)) {
             
            ps.setString(1, usuario);  // Asigna el nombre de usuario al primer ?
            ps.setString(2, password); // Asigna la contraseña al segundo ?

            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    LexisManage.idUsuario = rs.getInt("id_usuario");
                    JOptionPane.showMessageDialog(null, "Acceso permitido. Usuario encontrado: " + rs.getString("nombre_usuario"));
                    dispose();

                    MenuPrincipal menu = new MenuPrincipal();
                    menu.setVisible(true);
                    menu.setLocationRelativeTo(null);
                } else {
                    JOptionPane.showMessageDialog(null, "Acceso denegado. Usuario o contraseña incorrectos.");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(LOGIN.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Error al conectar con la base de datos.");
        }
    } else {
        JOptionPane.showMessageDialog(null, "Error al Iniciar Sesion. Por favor, completa todos los campos.");
    }
    }//GEN-LAST:event_BUTTONLOGINActionPerformed

    private void BUTTONREGISTERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTONREGISTERActionPerformed
        // TODO add your handling code here:
        dispose();
        REGISTRO registro = new REGISTRO();
        
        registro.setVisible(true);
        registro.setLocationRelativeTo(null);
    }//GEN-LAST:event_BUTTONREGISTERActionPerformed

    private void PASSWORDLOGINCAMPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PASSWORDLOGINCAMPOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PASSWORDLOGINCAMPOActionPerformed

    private void OLVIDASTEPASSWORDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OLVIDASTEPASSWORDMouseClicked
        // TODO add your handling code here:
        dispose();
        OLVIDASTE olvidaste = new OLVIDASTE();
        
        olvidaste.setVisible(true);
        olvidaste.setLocationRelativeTo(null);
    }//GEN-LAST:event_OLVIDASTEPASSWORDMouseClicked

    private void CERRARLOGINMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CERRARLOGINMouseClicked
        // TODO add your handling code here:
      Conexion.cerrarConexion();
        System.exit(0);
    }//GEN-LAST:event_CERRARLOGINMouseClicked

    private void USUARIOLOGINCAMPOMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_USUARIOLOGINCAMPOMousePressed
        // TODO add your handling code here:
        if(USUARIOLOGINCAMPO.getText().equals("ingrese su nombre de usuario")){
        USUARIOLOGINCAMPO.setText("");
        USUARIOLOGINCAMPO.setForeground(Color.black);
        }
        if(String.valueOf(PASSWORDLOGINCAMPO.getPassword()).isEmpty()){
        PASSWORDLOGINCAMPO.setText("******");
        PASSWORDLOGINCAMPO.setForeground(Color.gray);
        }
    }//GEN-LAST:event_USUARIOLOGINCAMPOMousePressed

    private void PASSWORDLOGINCAMPOMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PASSWORDLOGINCAMPOMousePressed
        // TODO add your handling code here:
        if(String.valueOf(PASSWORDLOGINCAMPO.getPassword()).equals("******")){
        PASSWORDLOGINCAMPO.setText("");
        PASSWORDLOGINCAMPO.setForeground(Color.BLACK);
        }
        
        if(USUARIOLOGINCAMPO.getText().isEmpty()){
        USUARIOLOGINCAMPO.setText("ingrese su nombre de usuario");
        USUARIOLOGINCAMPO.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_PASSWORDLOGINCAMPOMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BUTTONLOGIN;
    private javax.swing.JButton BUTTONREGISTER;
    private javax.swing.JLabel CERRARLOGIN;
    private javax.swing.JLabel LOGOLOGIN;
    private javax.swing.JLabel OLVIDASTEPASSWORD;
    private javax.swing.JLabel PASSWORDLOGIN;
    private javax.swing.JPasswordField PASSWORDLOGINCAMPO;
    private javax.swing.JLabel USUARIOLOGIN;
    private javax.swing.JTextField USUARIOLOGINCAMPO;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
