/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lexismanage.vista;

import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import lexismanage.Conexion;

/**
 *
 * @author alexi
 */
public class MenuConfiguracion extends javax.swing.JPanel {

    /**
     * Creates new form usuarios
     */
    Conexion Conexion=new Conexion();
    MenuEmpleados em=new MenuEmpleados();
    
    
    
    static String nameest;
    
   
    
    public MenuConfiguracion() {
        initComponents();
        mostrardatosest();
    }
    
    public void mostrardatosest() {
    String sql = "SELECT * FROM Personalizacion_Establecimiento";
    Connection con = null;
    PreparedStatement pt = null;
    ResultSet rs = null;

    try {
        con = Conexion.conectar();
        pt = con.prepareStatement(sql);
        rs = pt.executeQuery();
        
        if (rs.next()) {
            nameest = rs.getString("nombre");
            CONFIRNAME.setText(rs.getString("nombre"));
            CONFIRCORREO.setText(rs.getString("correo"));
            CONFIRTEL.setText(rs.getString("telefono"));
            CONFIRUBI.setText(rs.getString("ubicacion"));
        }
        
    } catch (Exception e) {
        e.printStackTrace(); // Agrega este para ver errores
    } finally {
        // Cerrar los recursos
        try {
            if (rs != null) {
                rs.close();
            }
            if (pt != null) {
                pt.close();
            }
            if (con != null) {
                con.close();
            }
        } catch (SQLException e) {
            e.printStackTrace(); // Agrega este para ver errores de cierre
        }
    }
}
    
    private void guardarConfiguracion(String nombre, String correo, String telefono, String ubicacion, int id_admin) {
    Connection con = Conexion.conectar();
    
    
    String checkQuery = "SELECT * FROM Personalizacion_Establecimiento WHERE id_admin = ?";
    
    try {
        PreparedStatement checkStmt = con.prepareStatement(checkQuery);
        checkStmt.setInt(1, id_admin);
        ResultSet rs = checkStmt.executeQuery();

        
        if (rs.next()) {
            
            String updateQuery = "UPDATE Personalizacion_Establecimiento SET nombre = ?, correo = ?, telefono = ?, ubicacion = ?, configurado = TRUE WHERE id_admin = ?";
            PreparedStatement updateStmt = con.prepareStatement(updateQuery);
            updateStmt.setString(1, nombre);
            updateStmt.setString(2, correo);
            updateStmt.setString(3, telefono);
            updateStmt.setString(4, ubicacion);
            updateStmt.setInt(5, id_admin);
            
            int filasActualizadas = updateStmt.executeUpdate();
            if (filasActualizadas > 0) {
                JOptionPane.showMessageDialog(null, "Configuración actualizada correctamente.");
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo actualizar la configuración.");
            }
        } else {
            // No existen registros, así que realizamos un INSERT
            String insertQuery = "INSERT INTO Personalizacion_Establecimiento (nombre, correo, telefono, ubicacion, id_admin) VALUES (?, ?, ?, ?, ?)";
            PreparedStatement insertStmt = con.prepareStatement(insertQuery);
            insertStmt.setString(1, nombre);
            insertStmt.setString(2, correo);
            insertStmt.setString(3, telefono);
            insertStmt.setString(4, ubicacion);
            insertStmt.setInt(5, id_admin);
            
            int filasInsertadas = insertStmt.executeUpdate();
            if (filasInsertadas > 0) {
                JOptionPane.showMessageDialog(null, "Configuración guardada correctamente.");
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo guardar la configuración.");
            }
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error en la operación: " + e.getMessage());
        System.out.println("SQLState: " + e.getSQLState());
        System.out.println("Error Code: " + e.getErrorCode());
    } finally {
        // Cerrar la conexión
        try {
            if (con != null && !con.isClosed()) {
                con.close();
            }
        } catch (SQLException e) {
            System.out.println("Error al cerrar la conexión: " + e.getMessage());
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Actualizarconfig = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoubiest = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        camponameest = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campocorreoest = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        campotelest = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CONFIRNAME = new javax.swing.JLabel();
        CONFIRCORREO = new javax.swing.JLabel();
        CONFIRTEL = new javax.swing.JLabel();
        CONFIRUBI = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(10, 16, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONFIGURACION");

        Actualizarconfig.setFont(new java.awt.Font("Yu Gothic UI", 3, 18)); // NOI18N
        Actualizarconfig.setForeground(new java.awt.Color(255, 77, 88));
        Actualizarconfig.setText("Actualizar");
        Actualizarconfig.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Actualizarconfig.setBorderPainted(false);
        Actualizarconfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarconfigActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gestion App");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ubicacion :");

        campoubiest.setBackground(new java.awt.Color(242, 242, 242));
        campoubiest.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        campoubiest.setForeground(new java.awt.Color(153, 153, 153));
        campoubiest.setText(" Ingrese Ubicacion");
        campoubiest.setToolTipText("");
        campoubiest.setBorder(null);
        campoubiest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campoubiestMousePressed(evt);
            }
        });
        campoubiest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoubiestActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre :");

        camponameest.setBackground(new java.awt.Color(242, 242, 242));
        camponameest.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        camponameest.setForeground(new java.awt.Color(153, 153, 153));
        camponameest.setText(" Ingrese Nombre Establecimiento");
        camponameest.setToolTipText("");
        camponameest.setBorder(null);
        camponameest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                camponameestMousePressed(evt);
            }
        });
        camponameest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camponameestActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Correo");

        campocorreoest.setBackground(new java.awt.Color(242, 242, 242));
        campocorreoest.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        campocorreoest.setForeground(new java.awt.Color(153, 153, 153));
        campocorreoest.setText(" Ingrese Correo");
        campocorreoest.setToolTipText("");
        campocorreoest.setBorder(null);
        campocorreoest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campocorreoestMousePressed(evt);
            }
        });
        campocorreoest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campocorreoestActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Telefono :");

        campotelest.setBackground(new java.awt.Color(242, 242, 242));
        campotelest.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        campotelest.setForeground(new java.awt.Color(153, 153, 153));
        campotelest.setText(" Ingrese Telefono Establecimiento");
        campotelest.setToolTipText("");
        campotelest.setBorder(null);
        campotelest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campotelestMousePressed(evt);
            }
        });
        campotelest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campotelestActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 77, 88));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nombre :");

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Correo");

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Telefono :");

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Ubicacion :");

        CONFIRNAME.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        CONFIRNAME.setForeground(new java.awt.Color(255, 255, 255));

        CONFIRCORREO.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        CONFIRCORREO.setForeground(new java.awt.Color(255, 255, 255));

        CONFIRTEL.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        CONFIRTEL.setForeground(new java.awt.Color(255, 255, 255));

        CONFIRUBI.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        CONFIRUBI.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CONFIRUBI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CONFIRNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CONFIRTEL, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7))
                    .addComponent(CONFIRCORREO, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CONFIRNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CONFIRCORREO, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CONFIRTEL, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CONFIRUBI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(9, 9, 9)))
                .addGap(34, 34, 34))
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Informacion Establecimiento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(camponameest, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campocorreoest, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campotelest, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoubiest, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Actualizarconfig, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(174, 174, 174)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 255, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(247, 247, 247))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(camponameest)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campocorreoest))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campotelest))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoubiest, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Actualizarconfig)
                        .addGap(329, 329, 329))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ActualizarconfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarconfigActionPerformed
        // TODO add your handling code here:
        
        guardarConfiguracion(camponameest.getText(), campocorreoest.getText(), campotelest.getText(), campoubiest.getText(), lexismanage.LexisManage.idUsuario);
        mostrardatosest();
        nameest=camponameest.getText();
        

    }//GEN-LAST:event_ActualizarconfigActionPerformed

    private void campoubiestMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoubiestMousePressed
        // TODO add your handling code here:
            em.clearField(campoubiest, " Ingrese Ubicacion");
        em.checkAndSetPlaceholder(camponameest," Ingrese Nombre Establecimiento");
        em.checkAndSetPlaceholder(campocorreoest, " Ingrese Correo");
        em.checkAndSetPlaceholder(campotelest, " Ingrese Telefono Establecimiento");
    }//GEN-LAST:event_campoubiestMousePressed

    private void campoubiestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoubiestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoubiestActionPerformed

    private void camponameestMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_camponameestMousePressed
        // TODO add your handling code here:
        em.clearField(camponameest," Ingrese Nombre Establecimiento");
        em.checkAndSetPlaceholder(campocorreoest, " Ingrese Correo");
        em.checkAndSetPlaceholder(campotelest, " Ingrese Telefono Establecimiento");
        em.checkAndSetPlaceholder(campoubiest, " Ingrese Ubicacion");
    }//GEN-LAST:event_camponameestMousePressed

    private void camponameestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camponameestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_camponameestActionPerformed

    private void campocorreoestMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campocorreoestMousePressed
        // TODO add your handling code here:
         em.clearField(campocorreoest, " Ingrese Correo");
        em.checkAndSetPlaceholder(camponameest," Ingrese Nombre Establecimiento");
        em.checkAndSetPlaceholder(campotelest, " Ingrese Telefono Establecimiento");
        em.checkAndSetPlaceholder(campoubiest, " Ingrese Ubicacion");
    }//GEN-LAST:event_campocorreoestMousePressed

    private void campocorreoestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campocorreoestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campocorreoestActionPerformed

    private void campotelestMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campotelestMousePressed
        // TODO add your handling code here:
        em.clearField(campotelest, " Ingrese Telefono Establecimiento");
        em.checkAndSetPlaceholder(camponameest," Ingrese Nombre Establecimiento");
        em.checkAndSetPlaceholder(campocorreoest, " Ingrese Correo");
        em.checkAndSetPlaceholder(campoubiest, " Ingrese Ubicacion");
    }//GEN-LAST:event_campotelestMousePressed

    private void campotelestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campotelestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campotelestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizarconfig;
    private javax.swing.JLabel CONFIRCORREO;
    private javax.swing.JLabel CONFIRNAME;
    private javax.swing.JLabel CONFIRTEL;
    private javax.swing.JLabel CONFIRUBI;
    private javax.swing.JTextField campocorreoest;
    private javax.swing.JTextField camponameest;
    private javax.swing.JTextField campotelest;
    private javax.swing.JTextField campoubiest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
