/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lexismanage.vista;

import java.awt.BorderLayout;
import javax.swing.JPanel;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import lexismanage.Conexion;

/**
 *
 * @author alexi
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN
     */
    
    MenuConfiguracion CON= new MenuConfiguracion();
    
    public MenuPrincipal() {
        initComponents();
         Conexion con=new Conexion();
        MenuUsuarios menu1= new MenuUsuarios();
        paneles(menu1);
        CON.mostrardatosest();
        NAMEEST.setText(CON.nameest);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        
       
       // this.setSize(1280, 720);
    }
    
    
    private void paneles(JPanel p){
        p.setSize(1298, 817);
        p.setLocation(0,0);
        
        contenido.removeAll();
        contenido.add(p, BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        LOGOLX = new javax.swing.JLabel();
        NAMEEST = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        pagosboton = new javax.swing.JLabel();
        usuariosboton = new javax.swing.JLabel();
        accesoboton = new javax.swing.JLabel();
        membresiasboton = new javax.swing.JLabel();
        empleadosboton = new javax.swing.JLabel();
        estadisticasboton = new javax.swing.JLabel();
        configurarboton = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        CERRARLOGIN = new javax.swing.JLabel();
        contenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(10, 16, 30));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(10, 16, 30));
        jPanel1.setForeground(new java.awt.Color(10, 16, 30));

        jPanel2.setBackground(new java.awt.Color(26, 39, 55));

        LOGOLX.setFont(new java.awt.Font("FRISTA", 3, 14)); // NOI18N
        LOGOLX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lexismanage/images/LM100.png"))); // NOI18N

        NAMEEST.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        NAMEEST.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(NAMEEST, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LOGOLX)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NAMEEST, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(LOGOLX, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(161, 161, 161))
        );

        jPanel4.setBackground(new java.awt.Color(10, 16, 30));

        pagosboton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lexismanage/images/pagosrojo.png"))); // NOI18N
        pagosboton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pagosbotonMouseClicked(evt);
            }
        });

        usuariosboton.setFont(new java.awt.Font("Yu Gothic UI", 3, 24)); // NOI18N
        usuariosboton.setForeground(new java.awt.Color(255, 255, 255));
        usuariosboton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lexismanage/images/usuariosATRAS.png"))); // NOI18N
        usuariosboton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usuariosbotonMouseClicked(evt);
            }
        });

        accesoboton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lexismanage/images/acceso.png"))); // NOI18N
        accesoboton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accesobotonMouseClicked(evt);
            }
        });

        membresiasboton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lexismanage/images/membresiasrojo.png"))); // NOI18N
        membresiasboton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                membresiasbotonMouseClicked(evt);
            }
        });

        empleadosboton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lexismanage/images/empleados.png"))); // NOI18N
        empleadosboton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empleadosbotonMouseClicked(evt);
            }
        });

        estadisticasboton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lexismanage/images/estadisticasrojo.png"))); // NOI18N
        estadisticasboton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                estadisticasbotonMouseClicked(evt);
            }
        });

        configurarboton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lexismanage/images/configurarrojo.png"))); // NOI18N
        configurarboton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                configurarbotonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(usuariosboton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(membresiasboton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accesoboton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pagosboton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(estadisticasboton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empleadosboton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(configurarboton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usuariosboton)
                    .addComponent(membresiasboton)
                    .addComponent(pagosboton)
                    .addComponent(accesoboton)
                    .addComponent(estadisticasboton)
                    .addComponent(empleadosboton)
                    .addComponent(configurarboton))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(26, 39, 55));

        CERRARLOGIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lexismanage/images/x lm.png"))); // NOI18N
        CERRARLOGIN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CERRARLOGINMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(1137, Short.MAX_VALUE)
                .addComponent(CERRARLOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CERRARLOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CERRARLOGINMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CERRARLOGINMouseClicked
        // TODO add your handling code here:
        Conexion.cerrarConexion();
        System.exit(0);
    }//GEN-LAST:event_CERRARLOGINMouseClicked

    private void usuariosbotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuariosbotonMouseClicked
        // TODO add your handling code here:
        
         MenuUsuarios Usuarios= new MenuUsuarios();
        paneles(Usuarios);
    }//GEN-LAST:event_usuariosbotonMouseClicked

    private void membresiasbotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_membresiasbotonMouseClicked
        // TODO add your handling code here:
        
        MenuMembresias membresias=new MenuMembresias();
        paneles(membresias);
    }//GEN-LAST:event_membresiasbotonMouseClicked

    private void accesobotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accesobotonMouseClicked
        // TODO add your handling code here:
        AccesoUsuarios acceso=new AccesoUsuarios();
        acceso.setVisible(true);
        acceso.setLocationRelativeTo(null);
    }//GEN-LAST:event_accesobotonMouseClicked

    private void pagosbotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pagosbotonMouseClicked
        // TODO add your handling code here:
        MenuPagos pagos =new MenuPagos();
        paneles(pagos);
                
    }//GEN-LAST:event_pagosbotonMouseClicked

    private void estadisticasbotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estadisticasbotonMouseClicked
        // TODO add your handling code here:
        MenuEstadisticas estadisticas= new MenuEstadisticas();
        paneles(estadisticas);
    }//GEN-LAST:event_estadisticasbotonMouseClicked

    private void empleadosbotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empleadosbotonMouseClicked
        // TODO add your handling code here:
        MenuEmpleados empleados = new MenuEmpleados();
        paneles(empleados);
    }//GEN-LAST:event_empleadosbotonMouseClicked

    private void configurarbotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configurarbotonMouseClicked
        // TODO add your handling code here:
        MenuConfiguracion configuracion= new MenuConfiguracion();
        paneles(configuracion);
    }//GEN-LAST:event_configurarbotonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CERRARLOGIN;
    private javax.swing.JLabel LOGOLX;
    private javax.swing.JLabel NAMEEST;
    private javax.swing.JLabel accesoboton;
    private javax.swing.JLabel configurarboton;
    private javax.swing.JPanel contenido;
    private javax.swing.JLabel empleadosboton;
    private javax.swing.JLabel estadisticasboton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel membresiasboton;
    private javax.swing.JLabel pagosboton;
    private javax.swing.JLabel usuariosboton;
    // End of variables declaration//GEN-END:variables
}
