/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lexismanage.vista;

import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import lexismanage.Conexion;

/**
 *
 * @author alexi
 */
public class OLVIDASTE extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN
     * 
     */
        REGISTRO RG=new REGISTRO();
        
    public OLVIDASTE() {
        initComponents();
        RG.mostrarcomboPregunta("Preguntas_Seguridad", "pregunta", jComboBox1);
         Conexion conexion= new Conexion();
        Conexion.conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        passwordregister = new javax.swing.JLabel();
        usuarioregister = new javax.swing.JLabel();
        usuarioregistercampo = new javax.swing.JTextField();
        Recuperarususario = new javax.swing.JButton();
        conpassregister = new javax.swing.JLabel();
        confirmarpascampo = new javax.swing.JPasswordField();
        usuarioregister1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        respaldo = new javax.swing.JLabel();
        respaldo1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        respuesta = new javax.swing.JLabel();
        passwordregistercampo1 = new javax.swing.JPasswordField();
        respaldo2 = new javax.swing.JLabel();
        respuestacampo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(10, 16, 30));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanel1.setBackground(new java.awt.Color(10, 16, 30));
        jPanel1.setForeground(new java.awt.Color(10, 16, 30));

        jPanel2.setBackground(new java.awt.Color(26, 39, 55));

        jLabel5.setFont(new java.awt.Font("FRISTA", 3, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lexismanage/images/LM100.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(26, 39, 55));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lexismanage/images/ATRASATRASATRAS.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(772, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        passwordregister.setFont(new java.awt.Font("Yu Gothic UI", 3, 24)); // NOI18N
        passwordregister.setForeground(new java.awt.Color(255, 255, 255));
        passwordregister.setText("Nueva Contraseña :");

        usuarioregister.setFont(new java.awt.Font("Yu Gothic UI", 3, 24)); // NOI18N
        usuarioregister.setForeground(new java.awt.Color(255, 255, 255));
        usuarioregister.setText("Usuario :");

        usuarioregistercampo.setBackground(new java.awt.Color(242, 242, 242));
        usuarioregistercampo.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        usuarioregistercampo.setForeground(new java.awt.Color(153, 153, 153));
        usuarioregistercampo.setText(" ingrese nombre de usuario");
        usuarioregistercampo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        usuarioregistercampo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usuarioregistercampoMousePressed(evt);
            }
        });
        usuarioregistercampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioregistercampoActionPerformed(evt);
            }
        });

        Recuperarususario.setBackground(new java.awt.Color(255, 77, 88));
        Recuperarususario.setFont(new java.awt.Font("Yu Gothic UI", 3, 18)); // NOI18N
        Recuperarususario.setForeground(new java.awt.Color(242, 242, 242));
        Recuperarususario.setText("Recuperar");
        Recuperarususario.setBorder(null);
        Recuperarususario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecuperarususarioActionPerformed(evt);
            }
        });

        conpassregister.setFont(new java.awt.Font("Yu Gothic UI", 3, 24)); // NOI18N
        conpassregister.setForeground(new java.awt.Color(255, 255, 255));
        conpassregister.setText("Confirmar Contraseña :");

        confirmarpascampo.setBackground(new java.awt.Color(242, 242, 242));
        confirmarpascampo.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        confirmarpascampo.setForeground(new java.awt.Color(153, 153, 153));
        confirmarpascampo.setText("*****");
        confirmarpascampo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        confirmarpascampo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                confirmarpascampoMousePressed(evt);
            }
        });

        usuarioregister1.setFont(new java.awt.Font("Yu Gothic UI", 3, 24)); // NOI18N
        usuarioregister1.setForeground(new java.awt.Color(255, 255, 255));
        usuarioregister1.setText("Respaldo");

        respaldo.setFont(new java.awt.Font("Yu Gothic UI", 3, 24)); // NOI18N
        respaldo.setForeground(new java.awt.Color(255, 255, 255));

        respaldo1.setFont(new java.awt.Font("Yu Gothic UI", 3, 24)); // NOI18N
        respaldo1.setForeground(new java.awt.Color(255, 255, 255));
        respaldo1.setText("Pregunta de seguridad:");

        jComboBox1.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        jComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        respuesta.setFont(new java.awt.Font("Yu Gothic UI", 3, 24)); // NOI18N
        respuesta.setForeground(new java.awt.Color(255, 255, 255));
        respuesta.setText("Respuesta :");

        passwordregistercampo1.setBackground(new java.awt.Color(242, 242, 242));
        passwordregistercampo1.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        passwordregistercampo1.setForeground(new java.awt.Color(153, 153, 153));
        passwordregistercampo1.setText("*****");
        passwordregistercampo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        passwordregistercampo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passwordregistercampo1MousePressed(evt);
            }
        });
        passwordregistercampo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordregistercampo1ActionPerformed(evt);
            }
        });

        respaldo2.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        respaldo2.setForeground(new java.awt.Color(255, 255, 255));
        respaldo2.setText("¡recuerda que la pregunta debe ser la misma que escogiste en el registro!");

        respuestacampo.setBackground(new java.awt.Color(242, 242, 242));
        respuestacampo.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        respuestacampo.setForeground(new java.awt.Color(153, 153, 153));
        respuestacampo.setText("Ingrese Su Respuesta");
        respuestacampo.setBorder(null);
        respuestacampo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                respuestacampoMousePressed(evt);
            }
        });
        respuestacampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respuestacampoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Recuperarususario, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(337, 337, 337))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmarpascampo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(usuarioregistercampo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(225, 225, 225)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(respaldo2, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usuarioregister, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordregistercampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(166, 166, 166)
                        .addComponent(usuarioregister1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(conpassregister, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordregister, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(respaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(respaldo1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(respuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(respuestacampo, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, 259, Short.MAX_VALUE)))))))
                .addGap(0, 146, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(usuarioregister1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usuarioregister, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(respaldo))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(usuarioregistercampo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(passwordregister))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(respaldo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(respaldo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(respuesta)
                        .addGap(14, 14, 14)
                        .addComponent(respuestacampo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(passwordregistercampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(conpassregister)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmarpascampo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(Recuperarususario, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioregistercampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioregistercampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioregistercampoActionPerformed

    private void RecuperarususarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecuperarususarioActionPerformed
        // TODO add your handling code here:
          String userReg = usuarioregistercampo.getText();
    String newpassreg = new String(passwordregistercampo1.getPassword());
    String conpassreg = new String(confirmarpascampo.getPassword());
    int idusuario;

    if (!userReg.isEmpty() && !newpassreg.isEmpty() && !conpassreg.isEmpty() && newpassreg.equals(conpassreg)) {
        Connection con = null;
        PreparedStatement pt = null;
        PreparedStatement pt2 = null;
        ResultSet rs = null;

        try {
            con = Conexion.conectar();
            String select = (String) jComboBox1.getSelectedItem();

            String verificarSQL = "SELECT SU.id_usuario " +
                                  "FROM Seguridad_UsuariosAdmin SU " +
                                  "JOIN USUARIO_ADMIN UA ON SU.id_usuario = UA.id_usuario " +
                                  "JOIN Preguntas_Seguridad PS ON SU.id_pregunta = PS.id_pregunta " +
                                  "WHERE UA.nombre_usuario = ? AND PS.pregunta = ? AND SU.respuesta_seguridad = ?";
            
            String actualizarSQL = "UPDATE USUARIO_ADMIN SET contrasena = ? WHERE id_usuario = ?";

            pt = con.prepareStatement(verificarSQL);
            pt.setString(1, userReg);
            pt.setString(2, select);
            pt.setString(3, respuestacampo.getText());
            rs = pt.executeQuery();

            if (rs.next()) {
                idusuario = rs.getInt("id_usuario");
                System.out.println(idusuario);

                pt2 = con.prepareStatement(actualizarSQL);
                pt2.setString(1, newpassreg);
                pt2.setInt(2, idusuario);
                int filas = pt2.executeUpdate();

                if (filas > 0) {
                    JOptionPane.showMessageDialog(null, "Contraseña actualizada, inicia sesión!");
                    this.dispose();
                    LOGIN log = new LOGIN();
                    log.setVisible(true);
                    log.setLocationRelativeTo(null);
                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo actualizar la contraseña. Usuario no encontrado o la pregunta/respuesta de seguridad no coinciden.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Usuario no encontrado. Asegúrate de escribir bien tu nombre de usuario.");
            }
        } catch (SQLException e) {
            e.printStackTrace(); 
            JOptionPane.showMessageDialog(null, "Error al realizar la operación: " + e.getMessage());
        } finally {
            
            try {
                if (rs != null) rs.close();
                if (pt != null) pt.close();
                if (pt2 != null) pt2.close();
                if (con != null) con.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    } else {
        JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden o los campos están vacíos.");
    }

        
    }//GEN-LAST:event_RecuperarususarioActionPerformed

    private void passwordregistercampo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordregistercampo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordregistercampo1ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked

        // TODO add your handling code here:
        
       dispose();
       
       LOGIN login = new LOGIN();
        
        login.setVisible(true);
        login.setLocationRelativeTo(null);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void usuarioregistercampoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioregistercampoMousePressed
        // TODO add your handling code here:
        if( usuarioregistercampo.getText().equals(" ingrese nombre de usuario")){
         usuarioregistercampo.setText("");
        usuarioregistercampo.setForeground(Color.black);
        }
        if(String.valueOf( passwordregistercampo1.getPassword()).isEmpty()){
        passwordregistercampo1.setText("*****");
        passwordregistercampo1.setForeground(Color.gray);
        }
        if(String.valueOf( confirmarpascampo.getPassword()).isEmpty()){
        confirmarpascampo.setText("*****");
        confirmarpascampo.setForeground(Color.gray);
        }
        
        if(respuestacampo.getText().isEmpty()){
            respuestacampo.setText("Ingrese Su Respuesta");
           respuestacampo.setForeground(Color.gray);
        }
    }//GEN-LAST:event_usuarioregistercampoMousePressed

    private void passwordregistercampo1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordregistercampo1MousePressed
        // TODO add your handling code here:
         if(String.valueOf( passwordregistercampo1.getPassword()).equals("*****")){
        passwordregistercampo1.setText("");
        passwordregistercampo1.setForeground(Color.black);
        }
        if(usuarioregistercampo.getText().isEmpty()){
            usuarioregistercampo.setText(" ingrese nombre de usuario");
            usuarioregistercampo.setForeground(Color.gray);
        }
        if(String.valueOf(confirmarpascampo.getPassword()).isEmpty()){
            confirmarpascampo.setText("*****");
            confirmarpascampo.setForeground(Color.gray);
        }
        if(respuestacampo.getText().isEmpty()){
            respuestacampo.setText("Ingrese Su Respuesta");
           respuestacampo.setForeground(Color.gray);
        }
    }//GEN-LAST:event_passwordregistercampo1MousePressed

    private void confirmarpascampoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmarpascampoMousePressed
        // TODO add your handling code here:
        if(String.valueOf( confirmarpascampo.getPassword()).equals("*****")){
        confirmarpascampo.setText("");
        confirmarpascampo.setForeground(Color.black);
        }
         
        if(usuarioregistercampo.getText().isEmpty()){
            usuarioregistercampo.setText(" ingrese nombre de usuario");
            usuarioregistercampo.setForeground(Color.gray);
        }
        
        if(String.valueOf( passwordregistercampo1.getPassword()).isEmpty()){
        passwordregistercampo1.setText("*****");
        passwordregistercampo1.setForeground(Color.gray);
        }
        
        if(respuestacampo.getText().isEmpty()){
            respuestacampo.setText("Ingrese Su Respuesta");
           respuestacampo.setForeground(Color.gray);
        }
    }//GEN-LAST:event_confirmarpascampoMousePressed

    private void respuestacampoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_respuestacampoMousePressed
        // TODO add your handling code here:
        if(respuestacampo.getText().equals("Ingrese Su Respuesta")){
            respuestacampo.setText("");
            respuestacampo.setForeground(Color.black);
        }

        if(usuarioregistercampo.getText().isEmpty()){
            usuarioregistercampo.setText(" ingrese nombre de usuario");
            usuarioregistercampo.setForeground(Color.gray);
        }

        if(String.valueOf( passwordregistercampo1.getPassword()).isEmpty()){
            passwordregistercampo1.setText("*****");
            passwordregistercampo1.setForeground(Color.gray);
        }

        if(String.valueOf(confirmarpascampo.getPassword()).isEmpty()){
            confirmarpascampo.setText("*****");
            confirmarpascampo.setForeground(Color.gray);
        }
    }//GEN-LAST:event_respuestacampoMousePressed

    private void respuestacampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respuestacampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_respuestacampoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OLVIDASTE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Recuperarususario;
    private javax.swing.JPasswordField confirmarpascampo;
    private javax.swing.JLabel conpassregister;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel passwordregister;
    private javax.swing.JPasswordField passwordregistercampo1;
    private javax.swing.JLabel respaldo;
    private javax.swing.JLabel respaldo1;
    private javax.swing.JLabel respaldo2;
    private javax.swing.JLabel respuesta;
    private javax.swing.JTextField respuestacampo;
    private javax.swing.JLabel usuarioregister;
    private javax.swing.JLabel usuarioregister1;
    private javax.swing.JTextField usuarioregistercampo;
    // End of variables declaration//GEN-END:variables
}
